name: Azure Deployment

on:
  push:
    branches:
      - main  # Despliega cuando se haga un push a la rama 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt

    - name: Build React app
      run: |
        cd frontend
        npm install
        npm run build
        cp -r build/* ../backend/static/

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'myapp-service'  # Reemplaza con el nombre de tu app service en Azure
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
